version: '3.9'
services:
  db:
    image: postgres:16
    container_name: poolup-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: poolup
      POSTGRES_PASSWORD: poolup
      POSTGRES_DB: poolup
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

