default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ios/PoolUp.xcodeproj")
    build_app(workspace: "ios/PoolUp.xcworkspace", scheme: "PoolUp")
    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "ios/PoolUp.xcodeproj")
    build_app(workspace: "ios/PoolUp.xcworkspace", scheme: "PoolUp")
    upload_to_app_store
  end
end
